export const CATEGORIES = {
  N2_GRAMMAR: "JLPT N2 文法",
  N1_GRAMMAR: "JLPT N1 文法",
  ELITE_ADVERBS: "Elite Adverbs",
  CONNECTORS: "Connectors",
  BUSINESS_VOCAB: "Business Japanese · ビジネス",
  N2_VERBS: "N2 動詞セット",
  CUSTOM: "Custom Quiz",
};

export const CATEGORY_GROUPS = [
  { label: "Grammar · 文法", cats: ["N2_GRAMMAR", "N1_GRAMMAR"] },
  { label: "Conversation · 会話", cats: ["ELITE_ADVERBS", "CONNECTORS"] },
  { label: "Vocabulary · 語彙", cats: ["BUSINESS_VOCAB", "N2_VERBS"] },
];

export const SIM_GROUPS = {
  contrast: ["一方（いっぽう）","反面（はんめん）","～にしろ～にしろ","といっても"],
  tendency: ["がち","つつある","～げ"],
  condition: ["ないことには","ものなら","としたら","たとえ～ても","としても"],
  addition: ["上に（うえに）","に加えて","のみならず","なおかつ"],
  reason: ["ことから","～とあって","～だけあって","わけだ"],
  degree: ["極めて","少なからず","極端に（きょくたんに）","格段に（かくだんに）","頻繁に"],
  negative: ["黙殺（もくさつ）","無能（むのう）","怠惰（たいだ）","堕落（だらく）"],
  emotion: ["落胆（らくたん）","後ろめたい（うしろめたい）","もどかしい","浮かない顔（うかないかお）"],
  work: ["昇進する（しょうしんする）","不採用（ふさいよう）","中途採用（ちゅうとさいよう）","倒産する（とうさん）","朝礼（ちょうれい）"],
  social: ["人付き合い（ひとづきあい）","雑談（ざつだん）","内気な（うちきな）","上がり症（あがりしょう）","会釈（えしゃく）"],
  business: ["了承（りょうしょう）","承諾（しょうだく）","拒否（きょひ）","依頼（いらい）","要請（ようせい）","交渉（こうしょう）","調整（ちょうせい）","締結（ていけつ）"],
  place_trap: ["幼稚園（ようちえん）","遊園地（ゆうえんち）"],
  carry: ["持参する（じさん）","所持する（しょじ）","所持（しょじ）"],
  camp_vibe: ["～派（は）","～系（けい）"],
};

export const ALL_DATA = [
  // N2 GRAMMAR
  { jp: "～から見ると", en: "from the perspective of", cat: "N2_GRAMMAR", num: 60, conn: "N＋", ex: "外国人から見ると、日本のマナーは厳しい。" },
  { jp: "～一方（いっぽう）", en: "on the other hand / while", cat: "N2_GRAMMAR", num: 61, conn: "普通形＋", ex: "便利な一方、高い。", kanjiStory: "一(one) + 方(direction) = looking at one direction only" },
  { jp: "～ことから", en: "because of the fact that", cat: "N2_GRAMMAR", num: 62, conn: "普通形＋", ex: "赤いことから、紅イモと呼ばれている。", kanjiStory: "こと(matter/fact) + から(from) = literally 'starting from the fact that ~' → reason inferred from situation." },
  { jp: "～のみならず", en: "not only ~ but also", cat: "N2_GRAMMAR", num: 63, conn: "普通形/N＋", ex: "若者のみならず大人も使っている。", kanjiStory: "のみ(only) + ならず(not staying as) = 'doesn't stop at only A, also B'. Classical/written register." },
  { jp: "～といった", en: "such as", cat: "N2_GRAMMAR", num: 64, conn: "N＋", ex: "寿司や天ぷらといった日本料理。", kanjiStory: "と(quote) + 言った(said) = 'said as ~' → introducing examples from a category." },
  { jp: "～にしたがって", en: "as ~ changes", cat: "N2_GRAMMAR", num: 65, conn: "V辞書形/N＋", ex: "年を取るにしたがって、体力が落ちる。", kanjiStory: "従う(to follow) + て-form → 'following along the change' → as A shifts, B follows in sync." },
  { jp: "～得る/得ない（うる/えない）", en: "possible / impossible", cat: "N2_GRAMMAR", num: 66, conn: "Vます形＋", ex: "そんなことはあり得ない。", kanjiStory: "得(gain) = something you can or cannot gain" },
  { jp: "～に反して", en: "contrary to", cat: "N2_GRAMMAR", num: 67, conn: "N＋", ex: "期待に反して、失敗した。" },
  { jp: "～に関して", en: "regarding", cat: "N2_GRAMMAR", num: 68, conn: "N＋", ex: "この問題に関して質問がある。" },
  { jp: "～反面（はんめん）", en: "on the flip side", cat: "N2_GRAMMAR", num: 69, conn: "普通形＋", ex: "便利な反面、危険もある。", kanjiStory: "反(flip) + 面(face) = flipping to see the other face" },
  { jp: "～上（じょう）", en: "in terms of / from standpoint", cat: "N2_GRAMMAR", num: 70, conn: "N＋", ex: "健康上の理由で辞めた。" },
  { jp: "～つつある", en: "gradually ~ing (process of change)", cat: "N2_GRAMMAR", num: 71, conn: "Vます形＋", ex: "状況が変わりつつある。", kanjiStory: "つつ(while doing) + ある(exist) = 'in the state of doing' → mid-transition, ongoing change." },
  { jp: "～に限らず（かぎらず）", en: "not limited to ~ / not just ~", cat: "N2_GRAMMAR", num: 72, conn: "N＋", ex: "水の問題は特定の地域に限らず、世界的な問題になるだろう。", kanjiStory: "限(limit) + らず(not) = not limited to" },
  { jp: "～願う（ねがう）", en: "polite request (formal written)", cat: "N2_GRAMMAR", num: 74, conn: "お＋Vます形/ご＋N＋", ex: "事故の状況をもう一度詳しくお話し願えますか。", kanjiStory: "願(wish) = humbly wishing for someone's action" },
  { jp: "～申し上げる（もうしあげる）", en: "humble offering (most formal)", cat: "N2_GRAMMAR", num: 75, conn: "お＋Vます形/ご＋N＋", ex: "被害に遭われた方に心からお見舞い申し上げます。", kanjiStory: "申(say humbly) + 上(up) = humbly offering words upward" },
  { jp: "～ばと思う", en: "I'd like / hope that ~ (soft wish)", cat: "N2_GRAMMAR", num: 76, conn: "V条件形＋", ex: "皆さんのご意見をお聞かせくださればと思っています。" },
  { jp: "～につきまして", en: "regarding ~ (formal business)", cat: "N2_GRAMMAR", num: 77, conn: "N＋", ex: "発売の時期につきましては、現在検討中でございます。", kanjiStory: "Super-polite form of について. 就(reach/concerning) + ます-style → keigo register 'regarding'." },
  { jp: "～のなんのって", en: "extremely / you wouldn't believe how ~", cat: "N2_GRAMMAR", num: 78, conn: "普通形/な形容詞だ＋", ex: "午前中、忙しかったのなんのって、トイレに行くひまもないくらいだった。", kanjiStory: "の何の(this and that) + って(quote) → 'I can't even describe how ~' — over-the-top emphasis." },
  { jp: "～たて", en: "freshly done / just ~", cat: "N2_GRAMMAR", num: 79, conn: "Vます形＋", ex: "このパン、できたてを買ってきたんだ。", kanjiStory: "From 立て(stood up) → 'just stood up from being made' → freshly done, like 'fresh-baked'." },
  { jp: "～ったら", en: "expressing frustration about someone", cat: "N2_GRAMMAR", num: 80, conn: "N＋", ex: "うちの犬ったら、私が浴衣着てたら、よその人と間違えてほえたのよ。", kanjiStory: "Casual contraction of といったら ('speaking of'). Used to vent recurring annoyance about someone." },
  { jp: "～ようになっている", en: "designed to / set up so that ~", cat: "N2_GRAMMAR", num: 81, conn: "V辞書形/Vない形＋", ex: "ほこりが鼻に入るとくしゃみが出て、自然にそれを外へ出すようになっています。", kanjiStory: "様(state) + になっている(has become) → 'has come to be the way ~' = designed/set up that way." },
  { jp: "～わけだ", en: "that's why / naturally ~ (realization)", cat: "N2_GRAMMAR", num: 82, conn: "普通形/な形容詞だ/Nだの＋", ex: "A:このチョコ、1粒1000円もするんだよ。B:え!だからおいしいわけだね。", kanjiStory: "訳(reason/meaning) + だ(is) → 'so THAT'S the reason' — the click moment when things make sense." },
  { jp: "～どころか", en: "far from ~ / not only not ~ but ~", cat: "N2_GRAMMAR", num: 83, conn: "普通形＋", ex: "高校生の時は、海外旅行どころか国内旅行もしたことがありませんでした。", kanjiStory: "所(place) + か(?) = not even close to that place" },
  { jp: "～ようでは / ～ようじゃ", en: "if it's the case that ~ (negative judgment)", cat: "N2_GRAMMAR", num: 84, conn: "V辞書形/Vない形＋", ex: "おしゃれに全然気を使わないようじゃ、社会人としてまずいんじゃない？", kanjiStory: "様(state/condition) + では(if it's like this) → 'if things are this way, that's bad'. Negative judgment." },
  { jp: "～ぶる", en: "pretend to be / act like", cat: "N2_GRAMMAR", num: 85, conn: "N/な形/い形＋", ex: "偉ぶるな。", kanjiStory: "From 振る(behave/act). Attached to a noun = 'put on the air of ~' → pretense, always slightly negative." },
  { jp: "～に限って", en: "of all times / Murphy's law", cat: "N2_GRAMMAR", num: 86, conn: "N＋", ex: "急いでいるときに限って電車が遅れる。" },
  { jp: "～ことだ", en: "should / best to (advice)", cat: "N2_GRAMMAR", num: 87, conn: "V辞書形/Vない形＋", ex: "もっと練習することだ。", kanjiStory: "こと(the matter) + だ(is) → 'the matter is that you should ~' = direct advice/admonition." },
  { jp: "～という＋N", en: "every single ~ (emphasis)", cat: "N2_GRAMMAR", num: 88, conn: "N＋", ex: "木という木が燃えた。", kanjiStory: "と(quote) + 言う(call) + N → 'every X you can call X' — every single one without exception." },
  { jp: "～ところだった", en: "almost ~ (close call)", cat: "N2_GRAMMAR", num: 89, conn: "V辞書形＋", ex: "遅刻するところだった。", kanjiStory: "所(place/point) → 'I was right at the point of ~ing' → close call, almost happened but didn't." },
  { jp: "～くらいなら", en: "rather than ~ (I'd prefer)", cat: "N2_GRAMMAR", num: 90, conn: "V辞書形＋", ex: "あの店に行くくらいなら自分で作る。", kanjiStory: "位(extent) + なら(if it's at that level) → 'if it'd come to A, I'd rather B' — preference between bad options." },
  { jp: "～まし（だ）", en: "better of two bad options (AよりBのほうがましだ)", cat: "N2_GRAMMAR", num: 91, conn: "普通形＋", ex: "嘘をつくより正直に言うほうがましだ。", kanjiStory: "From classical 増し(more/increase) → 'more preferable than the worse one'. Picking the lesser evil." },
  { jp: "～ものがある", en: "there's something ~ about it", cat: "N2_GRAMMAR", num: 92, conn: "普通形＋", ex: "心に響くものがある。", kanjiStory: "物(thing) + がある(exists) → 'there is a [quality] to it' — speaker's emotional reaction." },
  { jp: "～まい", en: "will probably never / refuses to", cat: "N2_GRAMMAR", num: 93, conn: "V辞書形＋", ex: "二度と会うまい。", kanjiStory: "Classical negative volitional from まじ → 'shall not / surely not'. Old-Japanese flavor in modern formal writing." },
  { jp: "～につけ", en: "whenever / every time (emotional)", cat: "N2_GRAMMAR", num: 94, conn: "V辞書形＋", ex: "ニュースを聞くにつけ不安になる。", kanjiStory: "付け(attach to) → 'every time something attaches to me, this feeling rises' → recurring emotional reaction." },
  { jp: "～わりに（は）", en: "considering / for (unexpected)", cat: "N2_GRAMMAR", num: 95, conn: "普通形/N＋", ex: "年のわりに若く見える。", kanjiStory: "割り(proportion/ratio) → 'compared to the proportion expected, the result is unexpected'." },
  { jp: "～うちに", en: "while / before it changes", cat: "N2_GRAMMAR", num: 96, conn: "V辞書形/Vない形＋", ex: "暗くならないうちに帰ろう。", kanjiStory: "内(inside) → 'while still inside the time-window of ~' → before the state changes, do it now." },
  { jp: "～げ", en: "seems ~ / has an air of ~", cat: "N2_GRAMMAR", num: 97, conn: "い形stem/な形＋", ex: "悲しげな顔。", kanjiStory: "Classical 気/げ suffix = 'has the air of ~'. Attaches to feelings: 楽し-げ(looks happy), 寂し-げ(looks lonely)." },
  { jp: "～やら～やら", en: "things like ~ and ~ (overwhelmed)", cat: "N2_GRAMMAR", num: 98, conn: "V辞書形/い形容詞/N＋", ex: "家賃やら交通費やら、お金がかかる。", kanjiStory: "やら from や(or) + ら(and others) → 'this and that and who knows what else' → overwhelmed by many things." },
  { jp: "～かと思うと", en: "just when I thought ~ (sudden)", cat: "N2_GRAMMAR", num: 99, conn: "Vた形＋", ex: "泣いたかと思うと笑い出した。" },
  { jp: "～にほかならない", en: "is none other than / precisely", cat: "N2_GRAMMAR", num: 100, conn: "N＋", ex: "努力の結果にほかならない。", kanjiStory: "他(other) + ならない(is not) = 'is nothing other than X' → emphasis: precisely X, definitely X." },
  { jp: "～にすぎない", en: "merely / nothing more than", cat: "N2_GRAMMAR", num: 101, conn: "V辞書形/N＋", ex: "10人にすぎない。", kanjiStory: "過ぎる(exceed) + ない(not) → 'does not exceed' → 'merely ~, nothing more'. Belittles the scale." },
  { jp: "～上に（うえに）", en: "on top of that / in addition", cat: "N2_GRAMMAR", num: 102, conn: "普通形/な形容詞だ/Nだの＋", ex: "高い上に、まずい。" },
  { jp: "～といっても", en: "even though I say (downplay)", cat: "N2_GRAMMAR", num: 103, conn: "普通形＋", ex: "日本語ができるといっても、まだN2だ。", kanjiStory: "と(quote) + 言って(saying) + も(even) → 'even though I say ~, actually ~'. Prepares for a downplay." },
  { jp: "～に限る", en: "nothing beats / best option is", cat: "N2_GRAMMAR", num: 104, conn: "V辞書形/N＋", ex: "疲れたときはビールに限る。" },
  { jp: "～だけあって", en: "as expected of / befitting", cat: "N2_GRAMMAR", num: 105, conn: "普通形/N＋", ex: "大阪だけあって、食べ物がうまい。", kanjiStory: "だけ(extent) + あって(having that much) → 'as expected of someone at that level' — praise, befitting." },
  { jp: "～にしろ～にしろ / にしても / にせよ", en: "whether ~ or ~ (either way)", cat: "N2_GRAMMAR", num: 106, conn: "普通形/な形容詞＋にしろ/N＋", ex: "賛成にしろ反対にしろ、理由を言え。", kanjiStory: "Classical imperative of する → 'whether you take A or B, the outcome is the same'." },
  { jp: "～とか", en: "I heard that (hearsay)", cat: "N2_GRAMMAR", num: 107, conn: "普通形＋", ex: "中止だとか。", kanjiStory: "と(quote) + か(uncertainty) → 'something like ~ I heard' — vague hearsay, source unclear." },
  { jp: "～にそって", en: "in accordance with / along", cat: "N2_GRAMMAR", num: 108, conn: "N＋", ex: "マニュアルにそって行う。", kanjiStory: "沿う(run along/parallel) → 'moving along the line of ~' → following a path, plan, or guideline." },
  { jp: "～にかけては", en: "when it comes to (pride)", cat: "N2_GRAMMAR", num: 109, conn: "N＋", ex: "料理にかけては誰にも負けない。", kanjiStory: "掛ける(stake on/hang on) → 'when it comes to staking it on this skill' → in this domain, no one beats me." },
  { jp: "～ないことには", en: "unless ~ (can't proceed)", cat: "N2_GRAMMAR", num: 110, conn: "Vない形＋", ex: "やってみないことには、わからない。", kanjiStory: "ないこと(the matter of NOT doing) + には → 'unless this happens, things can't proceed'. Strong precondition." },
  { jp: "～がち", en: "tend to (negative tendency)", cat: "N2_GRAMMAR", num: 111, conn: "Vます形/N＋", ex: "忘れがちだ。", kanjiStory: "From 勝ち(winning/dominant) → 'the dominant pattern is ~' → tends to (usually negative): 病気がち, 忘れがち." },
  { jp: "～つつ（も）", en: "although / while (contradiction)", cat: "N2_GRAMMAR", num: 112, conn: "Vます形＋", ex: "悪いと思いつつ、やめられない。", kanjiStory: "つつ(while doing) + も(even) → 'even while doing A, B contradicts'. Classical contrast register." },
  { jp: "～としたら", en: "if we suppose / hypothetically", cat: "N2_GRAMMAR", num: 113, conn: "普通形＋", ex: "転職するとしたら、ITがいい。", kanjiStory: "と(quote) + したら(if did) → 'if we suppose that ~'. と marks the supposition, したら is the if-form." },
  { jp: "～次第（しだい）", en: "depends on / as soon as", cat: "N2_GRAMMAR", num: 114, conn: "N/Vます形＋", ex: "努力次第だ。届き次第連絡します。", kanjiStory: "次(next) + 第(order) = what comes next in order" },
  { jp: "～一方（だ）", en: "keeps ~ing only (one direction)", cat: "N2_GRAMMAR", num: 115, conn: "V辞書形＋", ex: "物価は上がる一方だ。", kanjiStory: "一(one) + 方(direction) = going in one direction only" },
  { jp: "～に先立って", en: "prior to / before (formal)", cat: "N2_GRAMMAR", num: 116, conn: "N＋", ex: "開店に先立って試食会が開かれた。", kanjiStory: "先(ahead) + 立(stand) = standing ahead of everyone" },
  { jp: "～上で（うえで）", en: "after doing / based on", cat: "N2_GRAMMAR", num: 117, conn: "Vた形/Nの＋", ex: "相談した上で決める。" },
  { jp: "～にこたえて", en: "in response to (expectations)", cat: "N2_GRAMMAR", num: 118, conn: "N＋", ex: "期待にこたえて頑張った。", kanjiStory: "応える(answer/respond to) → 'in response to expectations/demand' → meeting hopes, formal." },
  { jp: "～ことにする", en: "decide to / pretend that", cat: "N2_GRAMMAR", num: 119, conn: "Vた形＋", ex: "聞かなかったことにする。", kanjiStory: "こと(matter) + にする(make it) → 'I make it the matter that ~' → 'I decide to ~' or 'I'll pretend ~'." },
  { jp: "～つもり", en: "believe mistakenly / thought I did", cat: "N2_GRAMMAR", num: 120, conn: "V辞書形/Vた形＋", ex: "送ったつもりだったが、送れていなかった。", kanjiStory: "From 積もり(accumulation) → 'piled-up intention' → 'I intended to ~' or 'I think I did, but actually didn't'." },
  { jp: "～てならない", en: "can't help but feel (overwhelming)", cat: "N2_GRAMMAR", num: 121, conn: "Vて形/い形くて＋", ex: "不思議でならない。", kanjiStory: "ならない(can't help becoming) → emotion is so strong you can't stop it. '~ to the point I can't bear it'." },
  { jp: "～ものなら", en: "if ~ could (challenge/warning)", cat: "N2_GRAMMAR", num: 122, conn: "V可能形＋", ex: "できるものなら、やってみろ。", kanjiStory: "もの(thing) + なら(if it could be) → 'if such a thing as ~ were possible' — challenge or wish." },
  { jp: "～うか～まいか", en: "whether to ~ or not (agonizing)", cat: "N2_GRAMMAR", num: 123, conn: "V意向形＋か＋V辞書形＋まいか", ex: "行こうか行くまいか悩んでいる。", kanjiStory: "Volitional う(will do) + classical まい(will not) → 'should I or shouldn't I?' — agonized indecision." },
  { jp: "～末に（すえに）", en: "after a long struggle/process", cat: "N2_GRAMMAR", num: 124, conn: "Vた形/Nの＋", ex: "考えた末に、決めた。", kanjiStory: "末(end/tip) = reaching the very tip after a long journey" },
  { jp: "～たとえ～ても", en: "even if (strong determination)", cat: "N2_GRAMMAR", num: 125, conn: "たとえ＋Vても＋", ex: "たとえ難しくても、あきらめない。", kanjiStory: "例え(even supposing) → 'even supposing the worst case, I still ~'. Strong determination." },
  { jp: "～がたい", en: "hard to / difficult to (emotionally)", cat: "N2_GRAMMAR", num: 126, conn: "Vます形＋", ex: "受け入れがたい。", kanjiStory: "難い(hard/difficult) → 'difficult to do' — emotionally, not physically. 信じがたい, 受け入れがたい." },
  { jp: "～もかまわず", en: "regardless of / not caring about", cat: "N2_GRAMMAR", num: 127, conn: "N＋", ex: "人目もかまわず泣いた。", kanjiStory: "構う(care/mind) + ず(not) → 'not caring even about ~' → ignoring social rules or others' feelings." },
  { jp: "～あまり（に）", en: "so much ~ that (excess → result)", cat: "N2_GRAMMAR", num: 128, conn: "V辞書形/な形な＋", ex: "心配するあまり痩せた。", kanjiStory: "余り(excess/too much) → 'so much ~ that as a result B happened'. Excessive cause leading to a result." },
  { jp: "～を込めて", en: "with (feeling/soul) put into", cat: "N2_GRAMMAR", num: 129, conn: "N＋", ex: "心を込めて作った。" },
  { jp: "～も～ば～も", en: "both ~ and ~ (balance)", cat: "N2_GRAMMAR", num: 130, conn: "N＋も＋V条件形＋N＋も", ex: "いいときもあれば悪いときもある。", kanjiStory: "も(also) + ば(if/and) + も(also) → 'A is true and B is also true' → balanced enumeration." },
  { jp: "～ぬく", en: "do thoroughly / endure to the end", cat: "N2_GRAMMAR", num: 131, conn: "Vます形＋", ex: "最後まで走りぬいた。", kanjiStory: "抜く(pull out/through) → 'do it ALL the way through to the end, no matter the difficulty'. Endurance." },
  { jp: "～ものだ", en: "used to ~ (nostalgia for past)", cat: "N2_GRAMMAR", num: 132, conn: "普通形（過去）＋", ex: "昔はよく遊んだものだ。", kanjiStory: "物(thing) + だ(is) → 'that's just how things are/were' → general truth or nostalgic recollection." },
  { jp: "～をめぐって", en: "concerning / over (dispute)", cat: "N2_GRAMMAR", num: 133, conn: "N＋", ex: "教育問題をめぐって議論した。", kanjiStory: "巡る(go around/revolve) → 'circling around the topic of ~' → debate or dispute centered on this." },
  { jp: "～わけだ", en: "no wonder / so that's why", cat: "N2_GRAMMAR", num: 134, conn: "普通形＋", ex: "毎日練習した。上手になったわけだ。", kanjiStory: "訳(reason/meaning) + だ(is) → 'so THAT'S the reason' — the click moment when things make sense." },
  { jp: "～にあたって", en: "on the occasion of (formal)", cat: "N2_GRAMMAR", num: 135, conn: "V辞書形/N＋", ex: "卒業にあたって、一言あいさつします。", kanjiStory: "当たる(hit/face) → 'at the moment of facing ~' → formal 'on the occasion of'. Ceremonies, transitions." },
  { jp: "～に加えて", en: "in addition to", cat: "N2_GRAMMAR", num: 136, conn: "N＋", ex: "経験に加えて、語学力も必要だ。" },
  // N1 GRAMMAR
  { jp: "～を皮切りに（かわきりに）", en: "starting with ~ then expanding", cat: "N1_GRAMMAR", num: 1, conn: "N/Vた+の＋", ex: "1974年を皮切りに全国に出店した。", kanjiStory: "皮(skin) + 切(cut) = the first surgical cut → starting point" },
  { jp: "～とあって", en: "given that (special → obvious result)", cat: "N1_GRAMMAR", num: 2, conn: "普通形＋", ex: "人気バンドが来ているとあって、ファンが集まった。", kanjiStory: "と(given that) + あって(it being) → 'given the special situation that ~' → specialness leads to obvious result." },
  { jp: "～ならではの", en: "unique to ~ / only ~ can offer", cat: "N1_GRAMMAR", num: 3, conn: "N＋ならではの＋N", ex: "海水浴は夏ならではのものだ。", kanjiStory: "なら(if it were) + では(no other) → 'something only ~ can offer' → unique to that source/era/person." },
  { jp: "～にもまして", en: "even more than ~ / more than ever", cat: "N1_GRAMMAR", num: 4, conn: "N/疑問詞＋にもまして", ex: "以前にもまして上手になった。", kanjiStory: "増す(increase/exceed) → 'even more than before' → comparison emphasizing greater degree than expected." },
  { jp: "～に至るまで（にいたるまで）", en: "all the way from ~ to ~ (full surprising range)", cat: "N1_GRAMMAR", num: 5, conn: "NからN＋に至るまで", ex: "子供からお年寄りに至るまで大阪弁を使う。", kanjiStory: "至(arrive) = arriving at the far extreme edge" },
  { jp: "～からして", en: "even just ~ (so imagine the rest)", cat: "N1_GRAMMAR", num: 6, conn: "N＋からして", ex: "声からしてかわいい。", kanjiStory: "から(from) + して(doing) → 'starting from just ~' → smallest detail mentioned implies the bigger picture." },
  { jp: "～に至っては（にいたっては）", en: "among a bad group, THIS one is the worst", cat: "N1_GRAMMAR", num: 7, conn: "N＋に至っては", ex: "兄弟は全員成績が悪いが、弟に至っては赤点ばかりだ。", kanjiStory: "至(reach) + っては = reaching the extreme point → THIS one is the worst" },
  { jp: "～といえども", en: "even X can't escape / even if ~", cat: "N1_GRAMMAR", num: 8, conn: "N＋といえども", ex: "社長といえども、法律には逆らえない。", kanjiStory: "Classical concessive: と(quote) + 言えど(though saying) + も(even) → 'even though one might say it's X, ~'." },
  { jp: "～を余儀なくされる（よぎなくされる）", en: "forced to do something (victim)", cat: "N1_GRAMMAR", num: 9, conn: "N＋を余儀なくされる", ex: "台風で避難を余儀なくされた。", kanjiStory: "余(surplus) + 儀(ceremony) = no surplus of options → forced" },
  { jp: "～たりとも…ない", en: "not even ONE, absolute zero", cat: "N1_GRAMMAR", num: 10, conn: "1＋助数詞＋たりとも…ない", ex: "一秒たりとも無駄にしたくない。", kanjiStory: "Old enumerative たり(even one example) + とも(even) + ない → 'not even one example exists' → absolute zero." },
  { jp: "～きらいがある", en: "has an undesirable tendency", cat: "N1_GRAMMAR", num: 11, conn: "Vる/Vない＋きらいがある", ex: "彼は人の話を聞かないきらいがある。", kanjiStory: "嫌い(dislike) → 'has a tendency that one would dislike' → bad/undesirable habit. Negative observation." },
  { jp: "～次第だ（N1）", en: "here's the reason (formal/business)", cat: "N1_GRAMMAR", num: 12, conn: "V普通形＋次第だ", ex: "ご連絡が遅れた次第です。", kanjiStory: "次(next) + 第(order) = explaining the order of events" },
  { jp: "～をもって / ～をもってすれば", en: "by means of (formal instrument)", cat: "N1_GRAMMAR", num: 13, conn: "N＋をもって", ex: "結果は書面（しょめん）をもってお知らせします。", kanjiStory: "持(hold) = wielding X as your tool to get it done", n5syn: "～で", oneLiner: "Wielding X as the tool to get it done." },
  { jp: "～あっての / ～あってのことだ", en: "only exists thanks to ~ (total gratitude)", cat: "N1_GRAMMAR", num: 14, conn: "N(A)＋あっての＋N(B)", ex: "学生あっての学校です。", kanjiStory: "有(exist) + って = because X EXISTS, Y is possible — total dependency", n5syn: "～のおかげで", oneLiner: "Without X, Y wouldn't exist — total gratitude mode." },
  { jp: "～てやまない", en: "can't stop feeling ~ (endlessly, formal)", cat: "N1_GRAMMAR", num: 15, conn: "Vて形＋やまない", ex: "おふたりの幸（しあわ）せを願ってやみません。", kanjiStory: "止(stop) + ない = the feeling won't stop flowing from the heart", n5syn: "ずっと～ている", oneLiner: "My heart keeps pouring this feeling — and will never stop." },
  { jp: "～まみれ", en: "covered in (gross/unwanted stuff)", cat: "N1_GRAMMAR", num: 16, conn: "N＋まみれ", ex: "借金（しゃっきん）まみれの生活から抜け出したい。", kanjiStory: "塗(smear/paint) = you're literally smeared/coated with X — can't wash it off. Usually written in kana. ONLY negative stuff (mud, blood, debt, scandal).", n5syn: "～だらけ", oneLiner: "Covered head-to-toe in something you WISH wasn't there." },
  { jp: "～をよそに", en: "ignoring ~ / regardless of ~ (often cold)", cat: "N1_GRAMMAR", num: 17, conn: "N＋をよそに", ex: "家族の心配をよそに、彼はゲームばかりしている。", kanjiStory: "余所 = 余(leftover) + 所(place) = 'the other place' → treat X as if it belongs somewhere else, not my problem", n5syn: "～を気にしないで", oneLiner: "Push it to the other room. Not my concern." },
  { jp: "～なりに / ～なりの", en: "in one's own way (doing best at that level, sympathetic)", cat: "N1_GRAMMAR", num: 18, conn: "N/普通形＋なりに(の)", ex: "子供は子供なりに自分の将来（しょうらい）についてよく考えている。", kanjiStory: "なり = the particular 'shape' a thing has → 'in its own shape' = fitting to what it is, always positive/sympathetic", n5syn: "～に合ったやり方で", oneLiner: "Not top-tier, but doing my best in my own shape." },
  { jp: "～なくもない / ～ないでもない", en: "it's not that ~ isn't so (weak, partial agreement)", cat: "N1_GRAMMAR", num: 19, conn: "Vない形＋でもない/もない", ex: "遠くから見ると、キャラクターに似ていなくもない。", kanjiStory: "double-negative logic: ない + でも/も + ない = 'not + not' = a vague YES you refuse to commit to. Stack two negatives to dodge a direct answer.", n5syn: "絶対に～ないとは言えない", oneLiner: "Not NOT true. Vaguely yes — but I refuse to commit." },
  { jp: "～始末だ（しまつだ）", en: "pathetic ending after a chain of bad choices (blame/let-down tone)", cat: "N1_GRAMMAR", num: 20, conn: "V辞書形/Vない形＋始末だ", ex: "毎晩飲み歩（あるい）た結果、仕事をクビになる始末だ。", kanjiStory: "始(begin) + 末(end) = the whole sad arc, start to finish → this is how it pathetically ended", n5syn: "最後には～になってしまう", oneLiner: "The whole miserable arc — and look how it ended." },
  { jp: "～なり～なり", en: "either A or B (advice; pick one, or anything similar)", cat: "N1_GRAMMAR", num: 21, conn: "V辞書形/N＋なり、V辞書形/N＋なり", ex: "分からない言葉があるときは、質問するなり辞書（じしょ）で調べるなりしなさい。", kanjiStory: "なり from 成り(become) = 'whether it becomes A or B' → A, B, or ANYTHING SIMILAR (open set of examples). Advisory register (しなさい/したらどう). NOT か〜か (finite facts) or にしろ〜にしろ (same result whichever).", n5syn: "～か～か (どちらでも)", oneLiner: "A or B or whatever — just pick something and do it." },
  { jp: "～ずくめ", en: "nothing but ~ / saturated entirely with ~ (fixed collocations only)", cat: "N1_GRAMMAR", num: 22, conn: "N＋ずくめ", ex: "先月（せんげつ）はいいことずくめだった。", kanjiStory: "From 尽くす(exhaust/use up) → saturated wall-to-wall with ~. CLOSED set only: 黒/白/いいこと/悪いこと/規則/異例/記録/ごちそう. Never 雨ずくめ or 犬ずくめ. vs まみれ(gross goo), だらけ(scattered neg), ばかり(free combo).", n5syn: "全部～だ / ～ばかり", oneLiner: "Nothing but ~. Zero exceptions." },
  { jp: "～にして", en: "both A and B (two coexisting qualities in one entity)", cat: "N1_GRAMMAR", num: 23, conn: "N/な形＋にして", ex: "彼は天才（てんさい）にして努力家（どりょくか）だ。", kanjiStory: "Classical にて(at/as) + し → 'being at state A, AND also B'. Celebrates the combo (no contradiction). Bonus: [number/age]にしてようやく = 'only at X, finally'. vs でありながら(contrast), と同時に(temporal), 一方で(opposing).", n5syn: "～でもあり、～でもある", oneLiner: "Two faces in one body — and both are real." },
  { jp: "～はおろか", en: "let alone ~ / not only A but even B is missing (dramatic absence)", cat: "N1_GRAMMAR", num: 24, conn: "N(A)＋はおろか＋N(B)＋も/さえ/すら/まで〜ない", ex: "イタリア語を勉強したことがないので、日常会話はおろか、あいさつさえできない。", kanjiStory: "愚(foolish, 心+禺=unthinking ape) → おろか = 'foolish to even mention'. A = obvious/big case (taken for granted), B = smaller/easier case that's ALSO missing — the shock is that even the tiny thing is gone. Always negative ending. vs どころか(reversal), に限らず(positive expansion), はもちろん(both exist).", n5syn: "Aはもちろん、Bも〜ない", oneLiner: "A is so obvious it's foolish to mention — and even B is gone too." },
  { jp: "～すら", en: "even ~ (literary; extreme example to imply the rest)", cat: "N1_GRAMMAR", num: 25, conn: "N(基本/最小)＋(に/で)＋すら〜ない", ex: "疲（つか）れて、立つことすらできない。", kanjiStory: "すら is the literary/elite upgrade of さえ. Attaches to the BASIC/MINIMUM thing — 'if even THIS is missing, you can imagine the rest is gone too.' Particles が/を usually drop (水すら飲めない ✓ NOT 水をすら ✗). Often pairs inside はおろか structures. Almost always negative ending.", n5syn: "～さえ / ～でも", oneLiner: "Even THIS — and you can imagine the rest." },
  // ELITE ADVERBS
  { jp: "そもそも", en: "in the first place (questioning fundamentals)", cat: "ELITE_ADVERBS", ex: "そもそも、何が原因なのか。", kanjiStory: "Older 抑(holding down/originally) doubled → 'going all the way back to the very beginning' = 'in the first place'." },
  { jp: "あえて", en: "dare to / deliberately choosing to", cat: "ELITE_ADVERBS", ex: "あえて言うなら、それは間違いだ。", kanjiStory: "From 敢う(to dare) → 'daringly/deliberately doing what you don't have to'. Going out of your way to ~." },
  { jp: "いわば", en: "so to speak / metaphorically", cat: "ELITE_ADVERBS", ex: "教育はいわば未来への投資だ。", kanjiStory: "From 言わば (literally 'if one were to say') → 'so to speak / metaphorically'. Drops in a comparison." },
  { jp: "果たして（はたして）", en: "I wonder if really (doubt)", cat: "ELITE_ADVERBS", ex: "果たして、それは正しいのだろうか。", kanjiStory: "果(fruit) = did it really bear fruit? → I wonder if really" },
  { jp: "少なからず（すくなからず）", en: "to no small extent / considerably", cat: "ELITE_ADVERBS", ex: "社会に少なからず影響がある。", kanjiStory: "少(few) + ず(not) = not few → to no small extent" },
  { jp: "とりわけ", en: "especially / in particular", cat: "ELITE_ADVERBS", ex: "とりわけ食文化に興味がある。", kanjiStory: "From 取り分ける(set aside specially) → 'singled out, set apart' → 'especially, in particular'." },
  // 極めて moved to MY_WORDS
  { jp: "むしろ", en: "rather / if anything (flipping)", cat: "ELITE_ADVERBS", ex: "むしろ、逆だと思う。", kanjiStory: "Classical 寧ろ(rather/sooner) → flips the listener's expectation: 'you'd think A, but if anything, B (the opposite)'." },
  // 頻繁に moved to MY_WORDS
  // CONNECTORS
  { jp: "なぜなら～からです", en: "because (formal reason-giving)", cat: "CONNECTORS", ex: "なぜなら、食べ物がおいしいからです。", kanjiStory: "何故(why) + なら(if asking) + から(because) → answers 'why?' formally. Lecture/essay register." },
  { jp: "確かに～しかし", en: "true, but... (counter-argument)", cat: "CONNECTORS", ex: "確かにそうだけど、私は反対だ。" },
  { jp: "しかしながら", en: "however (more elegant than しかし)", cat: "CONNECTORS", ex: "しかしながら、リスクもある。", kanjiStory: "しかし(however) + ながら(while) → 'however, while doing X' → softer, more elegant 'however' for formal speech." },
  { jp: "なおかつ（尚且つ）", en: "furthermore / and on top of that", cat: "CONNECTORS", ex: "安い、なおかつ品質もいい。", kanjiStory: "尚(still/even more) + 且つ(moreover/also) → 'on top of all that, still also' — stacking points formally." },
  // BUSINESS
  { jp: "了承（りょうしょう）", en: "acceptance / acknowledgment", cat: "BUSINESS_VOCAB", ex: "ご了承ください。", kanjiStory: "了(finish) + 承(receive) = received and done" },
  { jp: "承諾（しょうだく）", en: "consent / agreement", cat: "BUSINESS_VOCAB", ex: "承諾を得る。", kanjiStory: "承(receive) + 諾(agree) = received and agreed" },
  { jp: "拒否（きょひ）", en: "refusal / rejection", cat: "BUSINESS_VOCAB", ex: "要求を拒否する。", kanjiStory: "拒(refuse) + 否(deny) = refuse and deny" },
  { jp: "依頼（いらい）", en: "request (formal)", cat: "BUSINESS_VOCAB", ex: "仕事を依頼する。", kanjiStory: "依(rely) + 頼(ask) = rely on someone by asking" },
  { jp: "要請（ようせい）", en: "formal demand / strong request", cat: "BUSINESS_VOCAB", ex: "政府に要請する。", kanjiStory: "要(need) + 請(request) = needed request" },
  { jp: "交渉（こうしょう）", en: "negotiation", cat: "BUSINESS_VOCAB", ex: "給料について交渉する。", kanjiStory: "交(exchange) + 渉(wade) = wading through exchange" },
  { jp: "調整（ちょうせい）", en: "adjustment / coordination", cat: "BUSINESS_VOCAB", ex: "スケジュールを調整する。", kanjiStory: "調(tune) + 整(arrange) = tune and arrange" },
  { jp: "締結（ていけつ）", en: "contract conclusion / signing", cat: "BUSINESS_VOCAB", ex: "契約を締結する。", kanjiStory: "締(tie) + 結(bind) = tied and bound" },
  { jp: "契機（けいき）", en: "trigger / turning point", cat: "BUSINESS_VOCAB", ex: "これを契機に改善する。", kanjiStory: "契(promise) + 機(opportunity) = moment of commitment" },
  // N2 VERBS
  { jp: "収める（おさめる）", en: "to obtain / achieve results", cat: "N2_VERBS", ex: "成果を収める。", kanjiStory: "収(harvest) = harvesting results" },
  { jp: "補う（おぎなう）", en: "to supplement / compensate for", cat: "N2_VERBS", ex: "不足を補う。", kanjiStory: "補(patch) = patching up what's missing" },
  { jp: "及ぼす（およぼす）", en: "to exert / cause (influence)", cat: "N2_VERBS", ex: "影響を及ぼす。", kanjiStory: "及(reach) = reaching influence outward" },
  { jp: "妨げる（さまたげる）", en: "to obstruct / hinder", cat: "N2_VERBS", ex: "成長を妨げる。", kanjiStory: "妨(hinder) = a barrier blocking the way" },
  { jp: "蓄える（たくわえる）", en: "to store / accumulate", cat: "N2_VERBS", ex: "知識を蓄える。", kanjiStory: "蓄(store) = storing up reserves for later" },
  { jp: "費やす（ついやす）", en: "to spend / consume (time/money)", cat: "N2_VERBS", ex: "時間を費やす。", kanjiStory: "費(expense) = spending away resources" },
  { jp: "捉える（とらえる）", en: "to grasp / seize / perceive", cat: "N2_VERBS", ex: "チャンスを捉える。", kanjiStory: "捉(catch) = catching and grasping tight" },
  { jp: "養う（やしなう）", en: "to foster / nurture / develop", cat: "N2_VERBS", ex: "考える力を養う。", kanjiStory: "養(nurture) = feeding to help grow" },
  { jp: "避ける（よける）", en: "to dodge / avoid", cat: "N2_VERBS", ex: "危険を避ける。", kanjiStory: "避(avoid) = stepping aside to dodge" },
  { jp: "改める（あらためる）", en: "to renew / correct / reform", cat: "N2_VERBS", ex: "態度を改める。", kanjiStory: "改(reform) = breaking old to make new" },
  { jp: "怠る（おこたる）", en: "to neglect / be negligent", cat: "N2_VERBS", ex: "準備を怠る。", kanjiStory: "怠(lazy) = heart neglecting its duties" },
  { jp: "重んじる（おもんじる）", en: "to value / honor / respect", cat: "N2_VERBS", ex: "礼儀を重んじる。", kanjiStory: "重(heavy) = treating something as heavy → important" },
  { jp: "逆らう（さからう）", en: "to go against / defy", cat: "N2_VERBS", ex: "親に逆らう。", kanjiStory: "逆(reverse) = going the reverse way" },
  // CH01
  // CH02
  // CH04
  // 没入する moved to MY_WORDS
  // CH05
  // UNIT1 KANJI
  // UNIT2 KANJI
  // UNIT2 VOCAB
  // MY SAVED WORDS
  // ─── KEIGO VERBS (split out from old N2 #73 summary) ───
];

export const PASS_SCORE = 80;
export const QUESTIONS_PER_TEST = 30;
export const TIMER_SECONDS = 15 * 60;
